spring:
  application:
    name: users-app
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
server:
  servlet:
    context-path: /users-api
  port: 8082

logging:
  logback:
    rollingpolicy:
      max-file-size: 100MB
  level:
    root: info
    ru:
      lappi:
        users: debug
  file:
    name: "${user.dir}/log/users-service.log"
