
# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres-db:
    image: postgres:14.1-alpine3.15
    container_name: postgres-db
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:6.2
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8080:80
    depends_on:
      postgres-db:
        condition: service_healthy